first_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: link_joint_before
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: link_joint_after
    pid: {p: 100.0, i: 0.01, d: 10.0}
